version: 2
jobs:
   build:
     docker:
       - image: circleci/node:latest
     steps:
       - checkout
       - run: npm install
       - run: npx gulp build
       - run: node .circleci/deploy.js
       - run: echo "Finished deployment on i.cs.hku.hk"

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
